services:
  user-service:
    build:
      context: .
      target: user-service/Dockerfile

  payment-service:
    build:
      context: .
      target: payment-service/Dockerfile

  notification-service:
    build:
      context: .
      target: notification-service/Dockerfile

  information-service:
    build:
      context: .
      target: information-service/Dockerfile

  game-service:
    build:
      context: .
      target: game-service/Dockerfile


  mysqldb:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: mysql://database-users.mysql.database.azure.com:3306/
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD:


networks:
  app-network: