services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/user.env
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: ["java", "-jar", "target/user-service-0.0.1-SNAPSHOT.jar"]

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    env_file:
      - ./payment-service/payment.env
    ports:
      - "8081:8081"
    networks:
      - app-network
    command: ["java", "-jar", "target/payment-service-0.0.1-SNAPSHOT.jar"]

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/notification.env
    ports:
      - "8085:8085"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_RABBITMQ_PORT=5672
    - SPRING_RABBITMQ_USERNAME=guest
    - SPRING_RABBITMQ_PASSWORD=guest 
    networks:
      - app-network

  information-service:
    container_name: information-service
    build:
      context: ./information-service
      dockerfile: Dockerfile
    env_file:
      - ./information-service/information.env
    ports:
      - "8082:8082"
    networks:
      - app-network
    command: ["java", "-jar", "target/information-service-0.0.1-SNAPSHOT.jar"]

  game-service:
    container_name: game-service
    build:
      context: ./game-service
      dockerfile: Dockerfile
    env_file:
      - ./game-service/game.env
    ports:
      - "8083:8083"
    networks:
      - app-network
    command: ["java", "-jar", "target/game-service-0.0.1-SNAPSHOT.jar"]

networks:
  app-network:
    driver: bridge
