services:
  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/user.env
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: ["java", "-jar", "target/user-service-0.0.1-SNAPSHOT.jar"]

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    env_file:
      - ./payment-service/payment.env
    ports:
      - "8081:8080"
    networks:
      - app-network
    command: ["java", "-jar", "target/payment-service.jar"]

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/notification.env
    ports:
      - "8085:8080"
    networks:
      - app-network
    command: ["java", "-jar", "target/notification-service.jar"]

  information-service:
    container_name: information-service
    build:
      context: ./information-service
      dockerfile: Dockerfile
    env_file:
      - ./information-service/information.env
    ports:
      - "8082:8080"
    networks:
      - app-network
    command: ["java", "-jar", "target/information-service.jar"]

  game-service:
    container_name: game-service
    build:
      context: ./game-service
      dockerfile: Dockerfile
    env_file:
      - ./game-service/game.env
    ports:
      - "8083:8080"
    networks:
      - app-network
    command: ["java", "-jar", "target/game-service.jar"]

networks:
  app-network:
    driver: bridge