# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - lastman-standing-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ user, information, payment, game, notification ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Load Environment Variables
        run: |
            echo "${{secrets[env_matrix.service]}}" > [matrix.service].env
        env:
            user: USER_SERVICE_ENV
            payment: PAYMENT_SERVICE_ENV
            information: INFORMATION_SERVICE_ENV
            game: GAME_SERVICE_ENV
            notification: NOTIFICATION_SERVICE_ENV

      - name: Set-up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: build docker image
        uses: docker/build-push-action@v4
        with:   
          context: . 
          file: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME }}/rest-api:latest  

      - name: login to docker hub
        uses: docker/login-action@v1
        with:  
          username: ${{secrets.DOCKER_HUB_USERNAME }}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push image to docker hub  
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME }}/rest-api:latest

