# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - lastman-standing-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - name: CaoimhinHawk1
            docker_username: ${{secrets.DOCKER_HUB_USERNAME}}
            docker_access_token: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
          - name: CaoimheCahill
            docker_username: ${{secrets.DOCKER_HUB_USERNAME_CAOIMHE}}
            docker_access_token: ${{secrets.DOCKER_HUB_ACCESS_TOKEN_CAOIMHE}}
          - name: LiamMoMurray
            docker_username: ${{secrets.DOCKER_HUB_USERNAME_CAOIMHE}}
            docker_access_token: ${{secrets.DOCKER_HUB_ACCESS_TOKEN_CAOIMHE}}

        service: [user-service, notification-service, information-service]
 
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: unit tests
        run: mvn -B test --file pom.xml

      - name: Set-up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        if: matrix.user.name == github.actor
        uses: docker/login-action@v1
        with:
           username: ${{ matrix.user.docker_username }}
           password: ${{ matrix.user.docker_access_token }}

      - name: build docker image
        uses: docker/build-push-action@v4
        with:   
          context: . 
          file: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME }}/rest-api:latest  

      - name: login to docker hub
        uses: docker/login-action@v1
        with:  
          username: ${{secrets.DOCKER_HUB_USERNAME }}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push image to docker hub  
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME }}/rest-api:latest

