name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - '**'

jobs:
  sonarcloud:
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

          # Step 1: Run Maven tests with both unit and integration test profiles
      - name: Run Tests and Generate Coverage Reports
        run: |
          mvn clean verify -Pintegration-tests

      # Step 2: Run SonarCloud Analysis using the pre-generated reports
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=CS4437-Big-Data-Management-Team-1_LMS-Development-Repo \
            -Dsonar.organization=cs4437-big-data-management-team-1 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Post Job Summary
        if: always()
        run: |
          echo "SonarCloud analysis completed. Results available online: https://sonarcloud.io/project/overview?id=CS4437-Big-Data-Management-Team-1_LMS-Development-Repo"
